spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/gestiondestock

    password:
  jpa:
    database: MYSQL
    show-sql: false

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081


